export const Categories = [
  {label: 'Not selected', value: 'Unknown',
    children: [{label: 'nnn', value: 'bla'}, {label: 'nnn', value: 'la'}]},
  {label: 'Architecture and Engineering', value: 'Architecture and Engineering',
    children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Arts and Design', value: 'Arts and Design', children: [{label: 'nnn', value: 'bla'}, {label: 'iiii', value: 'la'}]},
  {label: 'Building and Grounds Cleaning', value: 'Building and Grounds Cleaning', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Business and Financial', value: 'Business and Financial', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Community and Social Service', value: 'Community and Social Service', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Computer and Information Technology', value: 'Computer and Information Technology', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Construction and Extraction', value: 'Construction and Extraction', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Education, Training, and Library', value: 'Education, Training, and Library', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Entertainment and Sports', value: 'Entertainment and Sports', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Farming, Fishing, and Forestry', value: 'Farming, Fishing, and Forestry', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Food Preparation and Serving', value: 'Food Preparation and Serving', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Healthcare', value: 'Healthcare', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Installation, Maintenance, and Repair', value: 'Installation, Maintenance, and Repair', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Legal', value: 'Legal', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Life, Physical, and Social Science', value: 'Life, Physical, and Social Science', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Management', value: 'Management', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Math', value: 'Math', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Media and Communication', value: 'Media and Communication', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Military', value: 'Military', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Office and Administration', value: 'Office and Administration', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Personal Care and Service', value: 'Personal Care and Service', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Production', value: 'Production', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Protective Service', value: 'Protective Service', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Sales', value: 'Sales', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Transportation and Material Moving', value: 'Transportation and Material Moving', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
];

/* export const Subcategories = {
  'Unknown': [],
  'Architecture and Engineering': [{label: 'aaaaa', value: 'aaaaa', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'bbb', value: 'bbbbb', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'c', value: 'ccccc'}],
  'Arts and Design': [{label: 'ooooo', value: 'oooo', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Building and Grounds Cleaning':  [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Business and Financial':  [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Community and Social Service':  [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Computer and Information Technology':  [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Construction and Extraction':  [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Education, Training, and Library': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Entertainment and Sports': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Farming, Fishing, and Forestry': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Food Preparation and Serving': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Healthcare': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Installation, Maintenance, and Repair': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Legal': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Life, Physical, and Social Science': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Management': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Math': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Media and Communication': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Military': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Office and Administration': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Personal Care and Service': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Production': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Protective Service': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Sales': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}],
  'Transportation and Material Moving': [{label: 'bla', value: 'bla', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'la', value: 'la', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]}, {label: 'a', value: 'a'}]
}; */


/* export const Subategories = [
  {label: 'Not selected', value: 'Unknown', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  {label: 'Architecture and Engineering', value: 'Architecture and Engineering', children: [{label: 'bla', value: 'bla'}, {label: 'bla', value: 'la'}]},
  'Arts and Design',
  'Building and Grounds Cleaning',
  'Business and Financial',
  'Community and Social Service',
  'Computer and Information Technology',
  'Construction and Extraction',
  'Education, Training, and Library',
  'Entertainment and Sports',
  'Farming, Fishing, and Forestry',
  'Food Preparation and Serving',
  'Healthcare',
  'Installation, Maintenance, and Repair',
  'Legal',
  'Life, Physical, and Social Science',
  'Management',
  'Math',
  'Media and Communication',
  'Military',
  'Office and Administration',
  'Personal Care and Service',
  'Production',
  'Protective Service',
  'Sales',
  'Transportation and Material Moving'
]; */
